CREATE USER smartmeal WITH PASSWORD 'smartmeal';
CREATE DATABASE smartmeal OWNER smartmeal;
GRANT ALL PRIVILEGES ON DATABASE smartmeal TO smartmeal;

\c smartmeal;

CREATE TABLE IF NOT EXISTS users (
  id SERIAL PRIMARY KEY,
  name VARCHAR(50) UNIQUE NOT NULL,
  goal VARCHAR(100)
);

CREATE TABLE IF NOT EXISTS pantry (
  id SERIAL PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  item TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS meal_plan (
  id SERIAL PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  title TEXT,
  created_at TIMESTAMP DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_users_name ON users(name);
CREATE INDEX IF NOT EXISTS idx_pantry_user ON pantry(user_id);